version: '3'
services:
  postgres:
    image: 'postgres:alpine'
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
  # ====================================================================================================================
  # PGADMIN
  # ====================================================================================================================
  # pgadmin-docker:
  #   image: dpage/pgadmin4
  #   container_name: dev-pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: me@example.com
  #     PGADMIN_DEFAULT_PASSWORD: 1234567
  #   ports:
  #     - 5050:80
  #   volumes:
  #     - ./.data/pgadmin:/var/lib/pgadmin
  #   depends_on:
  #     - pg-docker
  #   networks:
  #     - dev-network
# ======================================================================================================================
# REDE
# ======================================================================================================================
networks:
  dev-network:
    driver: bridge